//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUIA_LOGISTIC
    {
        public int guia_id { get; set; }
        public Nullable<int> guia_origen { get; set; }
        public Nullable<int> guia_destino { get; set; }
        public string guia_code { get; set; }
        public System.DateTime guia_date { get; set; }
        public Nullable<int> tras_id { get; set; }
        public Nullable<int> guia_status { get; set; }
        public string guia_lat { get; set; }
        public string guia_lon { get; set; }
        public string guia_latend { get; set; }
        public string guia_lonend { get; set; }
    }
}
