//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANS_LOGISTIC
    {
        public int tran_id { get; set; }
        public string tran_name { get; set; }
        public string tran_phone { get; set; }
        public string tran_user { get; set; }
        public string tran_password { get; set; }
    }
}
