//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vis_Tarifas
    {
        public int cost_id { get; set; }
        public int dest_ini { get; set; }
        public string origen { get; set; }
        public int dest_end { get; set; }
        public string destino { get; set; }
        public Nullable<double> dest_cost { get; set; }
        public Nullable<double> dest_cost_redondo { get; set; }
    }
}
